friends = ["Kevin","Playst","Jim","Tony","Steve","Tony"]
lucky_numbers = [4, 6, 5, 64, 68]
friends.extend(lucky_numbers)
print(friends)
friends.append("öpaaa")
print(friends)
friends.insert(1, "Mark")
print(friends)
friends.remove("Playst")
print(friends)
friends.pop()
print(friends)
print(friends.index("Tony"))
print(friends)
friends.count("Tony")
friends.pop()
friends.pop()
friends.pop()
friends.pop()
friends.pop()
friends.sort()
lucky_numbers.sort()
print(friends)
print(lucky_numbers)
lucky_numbers.reverse()
print(lucky_numbers)
print(friends)
friends2 = friends.copy
print(friends2)